// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycpvehytbmanpekvtvsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcHZlaHl0Ym1hbnBla3Z0dnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNDE1NjYsImV4cCI6MjA4NjkxNzU2Nn0.3r3ST9iagIRjQ50VANftDnisuLrjGTgkuMRujgDIOE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
